# Generated by Django 5.1.1 on 2024-10-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaibleslot',
            name='duration',
            field=models.DurationField(),
        ),
    ]
