# Generated by Django 5.1.1 on 2024-10-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0002_auto_20240923_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaibleslot',
            old_name='end',
            new_name='duration',
        ),
    ]
